<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CreoHub.Domain\CreoHub.Domain.csproj" />
      <ProjectReference Include="..\CreoHub.Infrastructure\CreoHub.Infrastructure.csproj" />
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

</Project>
